### PR TITLE
Download resume feature added

### PR DESCRIPTION
**Pull request by Aswin2255**
## Summary

This PR is about adding a new feature to download resume

### CODE REVIEW

**Comment by krishnaacharyaa** [comment]
Please add screenshot which gives us comparision between original live preview and the downloaded one

**Comment by Aswin2255** [comment]
@krishnaacharyaa 

https://github.com/krishnaacharyaa/profileFolio/assets/69797465/f56569d0-5aed-4e84-99fd-7298c37574d9

Global CSS is added to solve the issue with the borders it was mentioned in this https://github.com/parallax/jsPDF/issues/3532

**Comment by krishnaacharyaa** [comment]
Please try to select content in the pdf file

**Comment by krishnaacharyaa** [comment]
And then read this 
image

**Comment by krishnaacharyaa** [comment]
We cannot have images in the pdf @Aswin2255, in this the complete resume is snapshot into a canvas and then embeded on the pdf

**Pull request closed without merging**
