### PR TITLE
Fix/signup

### PR DESCRIPTION
**Pull request by pantha704**
- ## Passwords are now hashed before getting stored into db

- ### For SignUp provide : { name: , email: , password: } as a json object (as POST at localhost:8080/api/signup )

### CODE REVIEW

**Review by krishnaacharyaa — APPROVED** [review]
LGTM thanks

**Comment by krishnaacharyaa** [comment]
Please resolve merge conflicts @pantha704

**Comment by pantha704** [comment]
> Please resolve merge conflicts @pantha704

Done! @krishnaacharyaa

**Review by krishnaacharyaa — APPROVED** [review]
LGTM thanks

**Pull request merged**
